[2023-12-16T14:47:57.786+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: NYC_Taxi_data_pipeline.visualization manual__2023-12-16T14:22:27.349459+00:00 [queued]>
[2023-12-16T14:47:57.795+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: NYC_Taxi_data_pipeline.visualization manual__2023-12-16T14:22:27.349459+00:00 [queued]>
[2023-12-16T14:47:57.796+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-12-16T14:47:57.811+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): visualization> on 2023-12-16 14:22:27.349459+00:00
[2023-12-16T14:47:57.818+0000] {standard_task_runner.py:57} INFO - Started process 3167 to run task
[2023-12-16T14:47:57.821+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'NYC_Taxi_data_pipeline', 'visualization', 'manual__2023-12-16T14:22:27.349459+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/taxi_etl.py', '--cfg-path', '/tmp/tmpz0crc7xq']
[2023-12-16T14:47:57.824+0000] {standard_task_runner.py:85} INFO - Job 10: Subtask visualization
[2023-12-16T14:47:57.870+0000] {task_command.py:416} INFO - Running <TaskInstance: NYC_Taxi_data_pipeline.visualization manual__2023-12-16T14:22:27.349459+00:00 [running]> on host 6abb98cbcbb2
[2023-12-16T14:47:57.943+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='islam' AIRFLOW_CTX_DAG_ID='NYC_Taxi_data_pipeline' AIRFLOW_CTX_TASK_ID='visualization' AIRFLOW_CTX_EXECUTION_DATE='2023-12-16T14:22:27.349459+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-16T14:22:27.349459+00:00'
[2023-12-16T14:48:02.761+0000] {logging_mixin.py:154} INFO - Dash is running on http://0.0.0.0:8050/
[2023-12-16T14:48:02.761+0000] {dash.py:2053} INFO - Dash is running on http://0.0.0.0:8050/

[2023-12-16T14:48:02.768+0000] {logging_mixin.py:154} INFO -  * Serving Flask app '***'
[2023-12-16T14:48:02.769+0000] {logging_mixin.py:154} INFO -  * Debug mode: on
[2023-12-16T14:48:02.776+0000] {logging_mixin.py:154} WARNING - Address already in use
[2023-12-16T14:48:02.777+0000] {logging_mixin.py:154} WARNING - Port 8050 is in use by another program. Either identify and stop that program, or start the server with a different port.
[2023-12-16T14:48:02.813+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-16T14:48:02.828+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
